version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.7

    steps:
      - checkout

  # publish jobs require $DOCKER_USER, $DOCKER_PASS defined
  publish:
    docker:
      - image: cimg/python:3.7

    steps:
      - checkout

      - setup_remote_docker

      - run:
          command: |
            source ".circleci/parse-tag.sh"
            DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG"
            source ".circleci/push-image.sh"

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            # Example: Tor/0.4.3.6
            tags:
              only: /^[^/]+[/][0-9]+(\.[0-9]+)*(-[0-9]+)?/
